apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel
  namespace: spinnaker
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=50.0
        image: us-docker.pkg.dev/spinnaker-community/docker/keel:0.1.0-20210419190950-slim 
        name: keel
        ports:
        - name: traffic-port
          containerPort: 7010
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /health
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: keel-config-volume
        - mountPath: /var/secrets
          name: spinnaker-secrets-volume
      terminationGracePeriodSeconds: 720
      volumes:
      - name: keel-config-volume
        secret:
          secretName: keel-config
      - name: spinnaker-secrets-volume
        secret:
          secretName: spinnaker-secrets
